dist: xenial
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  matrix:
   - DJANGO="Django>=1.11,<2.0"
   - DJANGO="Django>=2.0,<2.1"
   - DJANGO="Django>=2.1,<2.2"
   - DJANGO="Django>=2.2,<3.0"
   - DJANGO="Django>=3.0a1,<3.1"
   - DJANGO="https://github.com/django/django/archive/master.tar.gz"

matrix:
  fast_finish: true
  exclude:
    # Django 2 dropped support for Python 2.
    - python: 2.7
      env: DJANGO="Django>=2.0,<2.1"
    - python: 2.7
      env: DJANGO="Django>=2.1,<2.2"
    - python: 2.7
      env: DJANGO="Django>=2.2,<3.0"
    - python: 2.7
      env: DJANGO="Django>=3.0a1,<3.1"
    - python: 2.7
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    # Django 2.1 dropped support for Python 3.4.
    - python: 3.4
      env: DJANGO="Django>=2.1,<2.2"
    - python: 3.4
      env: DJANGO="Django>=2.2,<3.0"
    - python: 3.4
      env: DJANGO="Django>=3.0a1,<3.1"
    - python: 3.4
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    # Django 3.0 dropped support for Python 3.5.
    - python: 3.5
      env: DJANGO="Django>=3.0a1,<3.1"
    - python: 3.5
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

install: pip install . $DJANGO
script: make test
